### ISSUE TITLE
Node installed but cannot find it when want to add it

### ISSUE THREAD

**Issue by Jeremy3191** [bramkn/n8n-nodes-run-node-with-credentials#1]
Hi Bram,

I am a low code beginner.
I just installed the node using npm i n8n-nodes-run-node-with-credentials-x but cannot find it when I want to add the node in one of my workflows.
Here a capture of the installation. Perhaps it didn't work well ?

<img width="523" alt="Capture d’écran 2024-02-20 à 10 36 55" src="https://github.com/bramkn/n8n-nodes-run-node-with-credentials/assets/160591925/f3f157d3-28cd-4cdd-8999-a87a84fd1442">

Thank you very much for your work !

Jeremy

**Comment by bramkn** [comment]
Hi Jeremy, 
This is not a question about the node but about installing custom nodes in general. Please ask on the n8n forum.
